# Generated by configure, do not edit. Edit Makefile.in instead
PREFIX = /usr/local
opt = -O3
dbg = -g
libdl = -ldl
CFLAGS_alloca = -DHAVE_ALLOCA_H
CFLAGS_xrandr = -DHAVE_XRANDR
LDFLAGS_xrandr = -lXrandr
gui_target = gui
